---
name: Test the application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint-and-scan:
    uses: dceoy/gh-actions-for-devops/.github/workflows/python-package-lint-and-scan.yml@main
    with:
      package-path: .
      python-version: '3.10'
      runs-on: windows-latest
      mypy-options: --exclude=build --install-types --non-interactive --ignore-missing-imports
  test-installation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install packages
        run: |
          pip install -r requirements.txt
