---
name: Test the application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint-and-scan:
    uses: dceoy/gh-actions-for-devops/.github/workflows/python-package-lint-and-scan.yml@main
    with:
      package-path: .
      python-version: '3.10'
      runs-on: windows-latest
      mypy-options: --exclude=build --install-types --non-interactive --ignore-missing-imports
